/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_bd;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author almas
 */
public class AgregarCUENTA extends javax.swing.JFrame {

    /**
     * Creates new form AgregarCUENTA
     */
    public AgregarCUENTA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfidpaciente = new javax.swing.JTextField();
        tfpaciente = new javax.swing.JTextField();
        tftelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfedad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfdireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfsexo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfregistroid = new javax.swing.JTextField();
        tftrasladoid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Id paciente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(21, 88, 130, 16);

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 140, 130, 16);

        jLabel3.setText("Telefono");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 190, 50, 16);
        getContentPane().add(tfidpaciente);
        tfidpaciente.setBounds(170, 90, 190, 22);
        getContentPane().add(tfpaciente);
        tfpaciente.setBounds(170, 140, 190, 22);
        getContentPane().add(tftelefono);
        tftelefono.setBounds(170, 190, 190, 22);

        jLabel4.setText("Cuenta");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 20, 120, 20);

        jLabel5.setText("Edad");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 240, 90, 16);
        getContentPane().add(tfedad);
        tfedad.setBounds(170, 240, 190, 22);

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 460, 67, 25);

        jButton2.setText("Eliminar");
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 460, 79, 25);

        jLabel6.setText("Direccion");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 280, 60, 20);
        getContentPane().add(tfdireccion);
        tfdireccion.setBounds(170, 280, 190, 22);

        jLabel7.setText("Sexo");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 330, 50, 16);
        getContentPane().add(tfsexo);
        tfsexo.setBounds(170, 320, 190, 22);

        jLabel8.setText("Registro_id");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 370, 80, 16);

        jLabel9.setText("Traslado_id");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 400, 67, 16);
        getContentPane().add(tfregistroid);
        tfregistroid.setBounds(170, 360, 190, 22);
        getContentPane().add(tftrasladoid);
        tftrasladoid.setBounds(170, 400, 190, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       grabar ();
    }//GEN-LAST:event_jButton1ActionPerformed

     public void grabar(){
              try  {    
        
     
       Connection con= DB.getConnection();
      PreparedStatement stmt=null;
      
      
      String  id_paciente = tfidpaciente.getText();
      String nombre=tfpaciente.getText();
      String telefono=tftelefono.getText();
      String edad=tfedad.getText();
      String direccion=tfdireccion.getText();
      String sexo=tfsexo.getText();
      String registro_id =tfregistroid.getText();
      String traslado_id=tftrasladoid.getText();
         
      
      String sql="  insert into paciente values( ";
      sql += id_paciente + ","+"\""+ nombre + "\""+",";
      sql += telefono+ ","+ edad +","+"\""+ direccion+"\""+","+"\""+sexo +"\""+","+registro_id+","+traslado_id + ")";
      
      JOptionPane.showMessageDialog(null,sql);
     
      
      
      stmt=con.prepareStatement(sql);
      int sw=stmt.executeUpdate();
       if (sw!=0) {
           JOptionPane.showMessageDialog(null,"Registrado de alta con éxito");
      
       }
       
   }
   catch (SQLException e2){
    JOptionPane.showMessageDialog(null,e2);
   } 
   catch (Exception e3){
   
   } 
   
    
    
    
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCUENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCUENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCUENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCUENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCUENTA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfdireccion;
    private javax.swing.JTextField tfedad;
    private javax.swing.JTextField tfidpaciente;
    private javax.swing.JTextField tfpaciente;
    private javax.swing.JTextField tfregistroid;
    private javax.swing.JTextField tfsexo;
    private javax.swing.JTextField tftelefono;
    private javax.swing.JTextField tftrasladoid;
    // End of variables declaration//GEN-END:variables
}
