/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_bd;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author almas
 */
public class checar_paciente extends javax.swing.JFrame {
ArrayList<paciente> lista = new ArrayList<paciente> ();
    /**
     * Creates new form checar_paciente
     */

  String IDPACIENTE ="";
     String NOMBRE ="";
     String TELEFONO ="";
     String  EDAD ="";
     String DIRECCION ="";
     String SEXO ="";
     String REGISTRO_IDREGISTRO="";
     String TRASLADO_IDTRASLADO="";
  
     
     

    public checar_paciente() {
        initComponents();
           jTable1.addMouseListener(new MouseAdapter() {
            
            DefaultTableModel model =new DefaultTableModel();
            
            public void mouseClicked (MouseEvent e){
                int i = jTable1.getSelectedRow();
           IDPACIENTE=(jTable1.getValueAt(i, 0).toString());
               NOMBRE =(jTable1.getValueAt(i,1).toString());
              TELEFONO  =(jTable1.getValueAt(i,2).toString());
                 EDAD=(jTable1.getValueAt(i, 0).toString());
              DIRECCION  =(jTable1.getValueAt(i,1).toString());
              SEXO  =(jTable1.getValueAt(i,2).toString());
               REGISTRO_IDREGISTRO  =(jTable1.getValueAt(i,1).toString());
              TRASLADO_IDTRASLADO =(jTable1.getValueAt(i,2).toString());
            }
            
            
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Id paciente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(25, 42, 63, 16);

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(25, 79, 45, 16);

        jLabel3.setText("Telefono");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(25, 119, 50, 16);

        jLabel4.setText("Edad");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(25, 159, 28, 16);

        jLabel5.setText("Direccion");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(25, 199, 52, 16);

        jLabel6.setText("Sexo");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(25, 239, 28, 16);

        jLabel7.setText("Registro_id registro");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(25, 279, 112, 16);

        jLabel8.setText("Traslado_id traslado");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(25, 319, 117, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(238, 39, 136, 22);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(238, 79, 204, 22);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(238, 119, 204, 22);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(238, 159, 204, 22);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(238, 199, 204, 22);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(238, 239, 204, 22);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(238, 279, 204, 22);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(238, 319, 204, 22);

        jButton1.setText("Nuevo");
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 380, 67, 25);

        jButton2.setText("Eliminar");
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 380, 79, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id paciente", "Nombre", "Telefono", "Edad", "Direccion", "Sexo", "Registro idregistro", "Traslado_idtraslado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(14, 445, 570, 134);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checar_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checar_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checar_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checar_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checar_paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
