/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_bd;

/**
 *
 * @author almas
 */
public class Estancia extends javax.swing.JInternalFrame {

    /**
     * Creates new form Estancia
     */
    public Estancia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jLabel1.setText("Id estancia");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 60, 94, 35);

        jLabel2.setText("Id listamedicamento");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 100, 120, 30);

        jLabel3.setText("Id listasintomas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 140, 104, 30);

        jLabel4.setText("Id listavisitas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 200, 73, 16);

        jLabel5.setText("Id cuarto");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 240, 73, 16);

        jLabel6.setText("Id listatratamiento");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 280, 104, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(170, 60, 115, 22);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(170, 100, 118, 22);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(170, 150, 118, 22);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(170, 200, 118, 22);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(170, 240, 118, 22);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(170, 280, 118, 22);

        jButton1.setText("Nuevo");
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 370, 67, 25);

        jButton2.setText("Agregar");
        getContentPane().add(jButton2);
        jButton2.setBounds(120, 370, 79, 25);

        jButton3.setText("Borrar");
        getContentPane().add(jButton3);
        jButton3.setBounds(220, 370, 69, 25);

        jButton4.setText("Modicar");
        getContentPane().add(jButton4);
        jButton4.setBounds(320, 370, 77, 25);

        jButton5.setText("Salir");
        getContentPane().add(jButton5);
        jButton5.setBounds(410, 370, 59, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
