/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_bd;

/**
 *
 * @author almas
 */
public class Registro extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Id registro");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 70, 81, 26);

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Id paciente ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 100, 90, 30);

        jLabel3.setText("Id traslado ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 140, 70, 20);

        jLabel4.setText("Id estancia ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 200, 90, 30);

        jLabel5.setText("Id listamedicos");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 230, 120, 50);

        jLabel6.setText("Fecha alta");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 280, 80, 30);

        jLabel7.setText("Fecha baja");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 320, 80, 40);

        jLabel8.setText("Urgencia");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(190, 370, 80, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(320, 70, 200, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(320, 110, 200, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(320, 160, 200, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(320, 200, 200, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(320, 240, 200, 30);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(320, 280, 200, 30);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(320, 320, 200, 30);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(320, 370, 200, 30);

        jButton1.setText("Nuevo");
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 440, 67, 25);

        jButton2.setText("Agregar ");
        getContentPane().add(jButton2);
        jButton2.setBounds(110, 440, 90, 25);

        jButton3.setText("Borrar");
        getContentPane().add(jButton3);
        jButton3.setBounds(230, 440, 80, 25);

        jButton4.setText("Modificar");
        getContentPane().add(jButton4);
        jButton4.setBounds(340, 440, 90, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
