/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_bd;

/**
 *
 * @author almas
 */
public class Traslado extends javax.swing.JInternalFrame {

    /**
     * Creates new form Traslado
     */
    public Traslado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jLabel1.setText("Id traslado ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(36, 36, 90, 37);

        jLabel2.setText("Sistomas");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(36, 91, 52, 16);

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(36, 128, 45, 16);

        jLabel4.setText("Edad");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(36, 168, 28, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(138, 43, 90, 22);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(138, 85, 290, 22);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(138, 125, 290, 22);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(138, 165, 100, 22);

        jButton1.setText("Nuevo");
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 230, 67, 25);

        jButton2.setText("Agregar ");
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 230, 83, 25);

        jButton3.setText("Borrar ");
        getContentPane().add(jButton3);
        jButton3.setBounds(240, 230, 73, 25);

        jButton4.setText("Modificar");
        getContentPane().add(jButton4);
        jButton4.setBounds(340, 230, 85, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
